#!/bin/bash
#set -eu
SCRIPT=$(readlink -f $0)
SCRIPTDIR="${SCRIPT%/*}"
BASEDIR="${SCRIPTDIR%/*}"
cd $BASEDIR

update()
{
	git pull -q || echo "git failed: $?"
	./install.sh
}

doit()
{
	set -eu
	[ -d site/$HOSTNAME/hourly ] && run-parts site/$HOSTNAME/hourly
	[ -d site/all/hourly ] && run-parts site/all/hourly
}


(update ; doit)  2>&1 | Mail -s "Automaton update $HOSTNAME" scott@griepentrog.com
