#!/bin/bash
#set -exu
SCRIPT=$(readlink -f $0)
SCRIPTDIR="${SCRIPT%/*}"
BASEDIR="${SCRIPTDIR%/*}"
cd $BASEDIR

update()
{
	echo "$HOSTNAME: $(uptime)"
	echo ""
	git pull
	echo "git returned $?"

	./install.sh
}

doit()
{
	set -exu
	[ -d host/$HOSTNAME/hourly ] && run-parts site/$HOSTNAME/hourly
	ls -l site/all/hourly
	[ -d host/all/hourly ] && run-parts site/all/hourly
}


(update ; doit)  2>&1 | Mail -s "Automaton update $HOSTNAME" scott@griepentrog.com
