#!/bin/bash
set -exu

echo "HOURLY SCRIPT RUNNING IN $PWD" | Mail -s "Automaton $HOSTNAME" scott@griepentrog.com

SCRIPT=$(readlink -f $0)
SCRIPTDIR="${SCRIPT%/*}"
BASEDIR="${SCRIPTDIR%/*}"

cd $BASEDIR

git pull

./install.sh
